services:
  php:
    build: ./docker/php
    volumes:
      - .:/var/www:delegated
    depends_on:
      - database
    networks:
      - veloCharbon

  nginx:
    build: ./docker/nginx
    ports:
     - "8000:80"
    volumes:
      - ./public:/var/www/public:delegated
    depends_on:
     - php
    networks:
      - veloCharbon           

  database:
    image: mariadb:latest
    environment:
      MARIADB_USER: "root"
      MARIADB_ROOT_PASSWORD: "test"
      MARIADB_DATABASE: "veloCharbon"
      MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: 'no'
    volumes:
      - database_data:/var/lib/mysql:rw
      - ./var/mysql:/var/www/var 
    networks:
      - veloCharbon

  adminer:
    image: adminer:latest
    depends_on:
      - database
    environment:
      APP_ENV: dev
      ADMINER_DESIGN: pepa-linha
      ADMINER_DEFAULT_SERVER: 
    ports:
      - "8082:8080"
    networks:
      - veloCharbon

networks:
  veloCharbon:

volumes:
  database_data:      